/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Cv1sabolAmbulanceWlList {
    }
}
declare global {
    interface HTMLCv1sabolAmbulanceWlListElement extends Components.Cv1sabolAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLCv1sabolAmbulanceWlListElement: {
        prototype: HTMLCv1sabolAmbulanceWlListElement;
        new (): HTMLCv1sabolAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "cv1sabol-ambulance-wl-list": HTMLCv1sabolAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface Cv1sabolAmbulanceWlList {
    }
    interface IntrinsicElements {
        "cv1sabol-ambulance-wl-list": Cv1sabolAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cv1sabol-ambulance-wl-list": LocalJSX.Cv1sabolAmbulanceWlList & JSXBase.HTMLAttributes<HTMLCv1sabolAmbulanceWlListElement>;
        }
    }
}
